### ISSUE TITLE
Code Release Issue

### ISSUE THREAD

**Issue by Shuyu-Hu** [Collebt/EM-CVGL#1]
Hi,
Thank you for sharing this fascinating work! I find it highly intriguing and am particularly curious about the implementation of the pipeline you described.
Do you have any plans to release the code repository? It would be immensely helpful for understanding and potentially building upon your work.
I look forward to your response.
Best.

**Comment by Collebt** [comment]
Thank you for your interest in our work. I have recently updated the code.
